# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage "https://github.com/aaron7/collabify"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/aaron7/collabify-cli/releases/download/v0.1.0/collabify-cli_Darwin_x86_64.tar.gz"
      sha256 "01089f606827e34baa97060b213966736137213c973e31a663a43c0b4c448649"

      def install
        bin.install "collabify"
      end
    end
    on_arm do
      url "https://github.com/aaron7/collabify-cli/releases/download/v0.1.0/collabify-cli_Darwin_arm64.tar.gz"
      sha256 "a8b1f5187c8a441c426f69005f6725c908f4d3c5b22ff5f88cfc46742566a40b"

      def install
        bin.install "collabify"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron7/collabify-cli/releases/download/v0.1.0/collabify-cli_Linux_x86_64.tar.gz"
        sha256 "13937c8abe80b3c67c0c6643e85b73f2afc9e127d035afb9157d7abd29dfd30e"

        def install
          bin.install "collabify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aaron7/collabify-cli/releases/download/v0.1.0/collabify-cli_Linux_arm64.tar.gz"
        sha256 "32fe957b44c1423c076e887554c7c0799b8ecedf8e8e019701987a0051a90ac4"

        def install
          bin.install "collabify"
        end
      end
    end
  end
end
